services:
  app:
    command: ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8088", "--reload"]
    volumes:
      - ./data:/app/data
      - ./app:/app/app
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
